[package]
name = "geoclue_fake"
version = "0.1.0"
authors = ["Grollicus <tobias-git@grollmann.eu>"]
edition = "2018"

[dependencies]
dbus = "0.6.4"
toml = "0.5.0"
serde = { version = "1.0.90", features = ["derive"] }
lazy_static = "1.3.0"
