[package]
name = "geoclue_fake"
version = "0.1.0"
authors = ["Grollicus <tobias-git@grollmann.eu>"]
edition = "2018"

[dependencies]
dbus = "0.8.4"
toml = "0.5.6"
serde = { version = "1.0.116", features = ["derive"] }
lazy_static = "1.4.0"
dbus-crossroads = "0.2.2"
